POST http://localhost:8080/api/evaluation
Content-Type: application/json

{"image","areas":[{"typeArea":"evaluated","start":{"x":297,"y":309},"height":0,"width":0,"end":{"x":479,"y":487},"color":"red","type":"Rectangle"},{"typeArea":"evaluated","start":{"x":297,"y":309},"height":0,"width":0,"end":{"x":479,"y":487},"color":"red","type":"Rectangle"}]}