CREATE TABLE "evaluaciones" (
                                "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "image" varchar,
                                "id_evaluador" int,
                                "image" varchar
);

CREATE TABLE "areas" (
                         "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "start_x" int,
                         "start_y" int,
                         "end_x" int,
                         "end_y" int,
                         "height" double precision,
                         "width" double precision,
                         "radio" double precision,
                         "type" varchar,
                         "type_area" varchar,
                         "id_evaluacion" int
);

CREATE TABLE "propetarios" (
                               "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "name" varchar
);

CREATE TABLE "evaluadores" (
                               "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "name" varchar
);

CREATE TABLE "terrenos" (
                            "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            "id_propietario" int,
                            "id_evaluacion" int
);

ALTER TABLE "areas" ADD FOREIGN KEY ("id_evaluacion") REFERENCES "evaluaciones" ("id");

ALTER TABLE "evaluaciones" ADD FOREIGN KEY ("id_evaluador") REFERENCES "evaluadores" ("id");

ALTER TABLE "terrenos" ADD FOREIGN KEY ("id_propietario") REFERENCES "propetarios" ("id");

ALTER TABLE "terrenos" ADD FOREIGN KEY ("id_evaluacion") REFERENCES "evaluaciones" ("id");


